# Generated by Django 3.2.20 on 2023-08-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App01Userinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'app01_userinfo',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('p_id', models.AutoField(db_column='P_id', primary_key=True, serialize=False)),
                ('p_name', models.CharField(db_column='P_name', max_length=256)),
                ('p_password', models.CharField(db_column='P_password', max_length=256)),
                ('p_sex', models.IntegerField(blank=True, db_column='P_sex', null=True)),
                ('p_age', models.IntegerField(blank=True, db_column='P_age', null=True)),
                ('p_birth', models.DateField(blank=True, db_column='P_birth', null=True)),
                ('p_word', models.CharField(blank=True, db_column='P_word', max_length=1024, null=True)),
                ('p_picture', models.TextField(blank=True, db_column='P_picture', null=True)),
                ('p_score', models.IntegerField(blank=True, db_column='P_score', null=True)),
                ('p_pro', models.CharField(blank=True, db_column='P_pro', max_length=256, null=True)),
                ('p_sp', models.CharField(blank=True, db_column='P_sp', max_length=256, null=True)),
                ('p_adm', models.IntegerField(blank=True, db_column='P_adm', null=True)),
            ],
            options={
                'db_table': 'People',
            },
        ),
        migrations.CreateModel(
            name='ProIndex',
            fields=[
                ('pro_id', models.IntegerField(db_column='Pro_id', primary_key=True, serialize=False)),
                ('pro_name', models.CharField(db_column='Pro_name', max_length=256)),
            ],
            options={
                'db_table': 'Pro_Index',
            },
        ),
        migrations.CreateModel(
            name='SchoolIndex',
            fields=[
                ('si_id', models.IntegerField(db_column='SI_id', primary_key=True, serialize=False)),
                ('si_name', models.CharField(db_column='SI_name', max_length=256)),
                ('img_1', models.CharField(blank=True, db_column='Img_1', max_length=1024, null=True)),
                ('img_2', models.CharField(blank=True, db_column='Img_2', max_length=1024, null=True)),
                ('img_3', models.CharField(blank=True, db_column='Img_3', max_length=1024, null=True)),
                ('img_4', models.CharField(blank=True, db_column='Img_4', max_length=1024, null=True)),
                ('img_5', models.CharField(blank=True, db_column='Img_5', max_length=1024, null=True)),
                ('img_6', models.CharField(blank=True, db_column='Img_6', max_length=1024, null=True)),
                ('img_name', models.CharField(blank=True, db_column='Img_name', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'School_Index',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('sc_id', models.IntegerField(db_column='SC_id', primary_key=True, serialize=False)),
                ('sc_name', models.CharField(db_column='SC_name', max_length=256)),
                ('sc_code_enroll', models.CharField(blank=True, db_column='SC_code_enroll', max_length=256, null=True)),
                ('sc_belong', models.CharField(blank=True, db_column='SC_belong', max_length=256, null=True)),
                ('sc_f985', models.IntegerField(blank=True, db_column='SC_f985', null=True)),
                ('sc_f211', models.IntegerField(blank=True, db_column='SC_f211', null=True)),
                ('sc_num_subject', models.IntegerField(blank=True, db_column='SC_num_subject', null=True)),
                ('sc_num_master', models.IntegerField(blank=True, db_column='SC_num_master', null=True)),
                ('sc_num_doctor', models.IntegerField(blank=True, db_column='SC_num_doctor', null=True)),
                ('sc_num_academician', models.IntegerField(blank=True, db_column='SC_num_academician', null=True)),
                ('sc_num_library', models.CharField(blank=True, db_column='SC_num_library', max_length=256, null=True)),
                ('sc_num_lab', models.IntegerField(blank=True, db_column='SC_num_lab', null=True)),
                ('sc_province_id', models.IntegerField(blank=True, db_column='SC_province_id', null=True)),
                ('sc_is_recruitment', models.IntegerField(blank=True, db_column='SC_is_recruitment', null=True)),
                ('sc_create_date', models.IntegerField(blank=True, db_column='SC_create_date', null=True)),
                ('sc_area', models.IntegerField(blank=True, db_column='SC_area', null=True)),
                ('sc_old_name', models.CharField(blank=True, db_column='SC_old_name', max_length=256, null=True)),
                ('sc_is_fenxiao', models.IntegerField(blank=True, db_column='SC_is_fenxiao', null=True)),
                ('sc_short', models.CharField(blank=True, db_column='SC_short', max_length=256, null=True)),
                ('sc_ruanke_rank', models.IntegerField(blank=True, db_column='SC_ruanke_rank', null=True)),
                ('sc_wsl_rank', models.IntegerField(blank=True, db_column='SC_wsl_rank', null=True)),
                ('sc_qs_rank', models.IntegerField(blank=True, db_column='SC_qs_rank', null=True)),
                ('sc_xyh_rank', models.IntegerField(blank=True, db_column='SC_xyh_rank', null=True)),
                ('sc_eol_rank', models.IntegerField(blank=True, db_column='SC_eol_rank', null=True)),
                ('sc_us_rank', models.IntegerField(blank=True, db_column='SC_us_rank', null=True)),
                ('sc_is_logo', models.IntegerField(blank=True, db_column='SC_is_logo', null=True)),
                ('sc_bdold_name', models.CharField(blank=True, db_column='SC_bdold_name', max_length=256, null=True)),
                ('sc_gbh_num', models.IntegerField(blank=True, db_column='SC_gbh_num', null=True)),
                ('sc_level_name', models.CharField(blank=True, db_column='SC_level_name', max_length=256, null=True)),
                ('sc_type_name', models.CharField(blank=True, db_column='SC_type_name', max_length=256, null=True)),
                ('sc_school_nature_name', models.CharField(blank=True, db_column='SC_school_nature_name', max_length=256, null=True)),
                ('sc_dual_class_name', models.CharField(blank=True, db_column='SC_dual_class_name', max_length=256, null=True)),
                ('sc_xueke_rank', models.CharField(blank=True, db_column='SC_xueke_rank', max_length=256, null=True)),
                ('sc_province_name', models.CharField(blank=True, db_column='SC_province_name', max_length=256, null=True)),
                ('sc_city_name', models.CharField(blank=True, db_column='SC_city_name', max_length=256, null=True)),
                ('sc_town_name', models.CharField(blank=True, db_column='SC_town_name', max_length=256, null=True)),
                ('sc_weiwangzhan', models.CharField(blank=True, db_column='SC_weiwangzhan', max_length=256, null=True)),
                ('sc_yjszs', models.CharField(blank=True, db_column='SC_yjszs', max_length=256, null=True)),
                ('sc_xiaoyuan', models.CharField(blank=True, db_column='SC_xiaoyuan', max_length=256, null=True)),
                ('sc_email', models.CharField(blank=True, db_column='SC_email', max_length=256, null=True)),
                ('sc_school_email', models.CharField(blank=True, db_column='SC_school_email', max_length=256, null=True)),
                ('sc_address', models.CharField(blank=True, db_column='SC_address', max_length=256, null=True)),
                ('sc_postcode', models.CharField(blank=True, db_column='SC_postcode', max_length=256, null=True)),
                ('sc_site', models.CharField(blank=True, db_column='SC_site', max_length=256, null=True)),
                ('sc_school_site', models.CharField(blank=True, db_column='SC_school_site', max_length=256, null=True)),
                ('sc_phone', models.CharField(blank=True, db_column='SC_phone', max_length=256, null=True)),
                ('sc_content', models.CharField(blank=True, db_column='SC_content', max_length=1024, null=True)),
                ('sc_dualclass', models.CharField(blank=True, db_column='SC_dualclass', max_length=1024, null=True)),
                ('sc_special', models.CharField(blank=True, db_column='SC_special', max_length=1024, null=True)),
                ('sc_nature_name', models.CharField(blank=True, db_column='SC_nature_name', max_length=256, null=True)),
                ('sc_province_score_year', models.IntegerField(blank=True, db_column='SC_province_score_year', null=True)),
                ('sc_qs_world', models.CharField(blank=True, db_column='SC_qs_world', max_length=256, null=True)),
                ('sc_fenxiao', models.CharField(blank=True, db_column='SC_fenxiao', max_length=1024, null=True)),
                ('sc_gbh_url', models.CharField(blank=True, db_column='SC_gbh_url', max_length=1024, null=True)),
                ('sc_jobrate', models.CharField(blank=True, db_column='SC_jobrate', max_length=1024, null=True)),
                ('sc_job_province', models.CharField(blank=True, db_column='SC_job_province', max_length=1024, null=True)),
                ('sc_attr', models.CharField(blank=True, db_column='SC_attr', max_length=1024, null=True)),
                ('sc_company', models.CharField(blank=True, db_column='SC_company', max_length=4096, null=True)),
                ('sc_vote', models.CharField(blank=True, db_column='SC_vote', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'School_Info',
            },
        ),
        migrations.CreateModel(
            name='SchoolLogal',
            fields=[
                ('logao_id', models.IntegerField(db_column='Logao_id', primary_key=True, serialize=False)),
                ('logal_name', models.CharField(blank=True, db_column='Logal_name', max_length=256, null=True)),
                ('logal_data', models.TextField(blank=True, db_column='Logal_data', null=True)),
            ],
            options={
                'db_table': 'School_Logal',
            },
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('st_id', models.BigAutoField(db_column='ST_id', primary_key=True, serialize=False)),
                ('st_school_name', models.CharField(db_column='ST_School_name', max_length=256)),
                ('st_year', models.IntegerField(blank=True, db_column='ST_Year', null=True)),
                ('st_type', models.CharField(blank=True, db_column='ST_Type', max_length=256, null=True)),
                ('st_spname', models.CharField(blank=True, db_column='ST_Spname', max_length=1024, null=True)),
                ('st_max', models.IntegerField(blank=True, db_column='ST_Max', null=True)),
                ('st_min', models.IntegerField(blank=True, db_column='ST_Min', null=True)),
                ('st_average', models.IntegerField(blank=True, db_column='ST_Average', null=True)),
                ('st_min_section', models.IntegerField(blank=True, db_column='ST_Min_section', null=True)),
                ('st_info', models.CharField(blank=True, db_column='ST_Info', max_length=1024, null=True)),
                ('st_level1_name', models.CharField(blank=True, db_column='ST_Level1_name', max_length=256, null=True)),
                ('st_level2_name', models.CharField(blank=True, db_column='ST_Level2_name', max_length=256, null=True)),
                ('st_level3_name', models.CharField(blank=True, db_column='ST_Level3_name', max_length=256, null=True)),
                ('st_zslx_name', models.CharField(blank=True, db_column='ST_Zslx_name', max_length=256, null=True)),
                ('st_local_batch_name', models.CharField(blank=True, db_column='ST_Local_batch_name', max_length=256, null=True)),
                ('st_sg_info', models.CharField(blank=True, db_column='ST_Sg_info', max_length=1024, null=True)),
                ('st_sg_xuanke', models.CharField(blank=True, db_column='ST_Sg_xuanke', max_length=1024, null=True)),
                ('pro', models.ForeignKey(db_column='Pro_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app01.proindex')),
                ('si', models.ForeignKey(db_column='SI_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app01.schoolindex')),
            ],
            options={
                'db_table': 'Score_Table',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('n_id', models.AutoField(db_column='N_id', primary_key=True, serialize=False)),
                ('n_name', models.CharField(blank=True, db_column='N_name', max_length=256, null=True)),
                ('n_info', models.CharField(blank=True, db_column='N_info', max_length=1024, null=True)),
                ('p', models.ForeignKey(db_column='P_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app01.people')),
            ],
            options={
                'db_table': 'Notice',
            },
        ),
    ]
